#!/usr/bin/env node
// aggregate.mjs — merge probe/reports/*.report.json + registry/*.json into
// data/conformance.js (a classic script that sets window.__ACP_WALL__), so the
// static demos can consume real probe results over file:// without fetch/CORS.
//
// usage: node tools/aggregate.mjs [--reports probe/reports] [--registry registry] [--out data/conformance.js]

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";

const root = resolve(dirname(new URL(import.meta.url).pathname), "..");
const arg = (f, d) => { const i = process.argv.indexOf(f); return i >= 0 ? process.argv[i + 1] : d; };
const reportsDir = resolve(root, arg("--reports", "probe/reports"));
const registryDir = resolve(root, arg("--registry", "registry"));
const out = resolve(root, arg("--out", "data/conformance.js"));

const CAPS = ["initialize", "authenticate", "session/new", "session/load", "session/prompt",
  "sessions/*", "set_mode", "set_config", "cancel", "logout",
  "message*", "tool_call*", "permission", "plan", "slash_cmds",
  "fs/*", "terminal/*", "elicitation", "mcp"];

// registry: name → entry. Sources: registry/*.json (hand-written, incl.
// selftest fixtures) and registry/agents/*.json (synced from the official
// ACP registry). selftest entries are probed in CI but never published.
const registry = {};
function loadRegistryDir(dir) {
  if (!existsSync(dir)) return;
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".json") && !f.startsWith("_"))) {
    try {
      const e = JSON.parse(readFileSync(join(dir, f), "utf8"));
      if (e.name) registry[e.name] = e;
    } catch (e) {
      console.warn(`skip ${dir}/${f}: ${e.message}`);
    }
  }
}
loadRegistryDir(registryDir);
loadRegistryDir(join(registryDir, "agents"));

const harnesses = [];
if (existsSync(reportsDir)) {
  for (const f of readdirSync(reportsDir).filter((f) => f.endsWith(".report.json"))) {
    let r;
    try {
      r = JSON.parse(readFileSync(join(reportsDir, f), "utf8"));
    } catch (e) {
      console.warn(`skip ${f}: ${e.message}`);
      continue;
    }
    const reg = registry[r.harness] ?? {};
    if (reg.selftest) {
      console.log(`  (selftest, not published: ${r.harness})`);
      continue;
    }
    harnesses.push({
      n: reg.display ?? reg.name ?? r.harness,
      v: [reg.vendor, r.agentVersion ? `v${r.agentVersion}` : null].filter(Boolean).join(" — "),
      desc: reg.description ?? null,
      icon: reg.icon ?? null,
      url: reg.website ?? (reg.repo ? `https://github.com/${reg.repo}` : null),
      tier: r.tier,
      cells: r.cells,
      notes: r.notes ?? {},
      score: r.score,
      version: r.agentVersion,
      probedAt: r.probedAt,
      run: reg.run ?? null,
      repo: reg.repo ?? null,
      dishonesty: r.dishonesty ?? [],
      violations: r.violations ?? [],
      star: r.tier === "verified" && r.score === 100 ? 1 : 0,
      _file: f,
    });
  }
}

harnesses.sort((a, b) => b.score - a.score);

const payload = {
  generatedAt: new Date().toISOString(),
  caps: CAPS,
  harnesses: harnesses.map(({ _file, ...h }) => h),
};

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// generated by tools/aggregate.mjs — do not edit\n` +
    `window.__ACP_WALL__ = ${JSON.stringify(payload, null, 2)};\n`
);
console.log(`aggregated ${harnesses.length} report(s) → ${out}`);
for (const h of harnesses) console.log(`  ${h.tier.padEnd(8)} ${String(h.score).padStart(3)}  ${h.n}`);
