#!/usr/bin/env node
// aggregate.mjs — merge probe/reports/*.report.json + registry/*.json into
// data/conformance.js (a classic script that sets window.__ACP_WALL__), so the
// static demos can consume real probe results over file:// without fetch/CORS.
//
// usage: node tools/aggregate.mjs [--reports probe/reports] [--registry registry] [--out data/conformance.js]

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";

const root = resolve(dirname(new URL(import.meta.url).pathname), "..");
const arg = (f, d) => { const i = process.argv.indexOf(f); return i >= 0 ? process.argv[i + 1] : d; };
const reportsDir = resolve(root, arg("--reports", "probe/reports"));
const registryDir = resolve(root, arg("--registry", "registry"));
const out = resolve(root, arg("--out", "data/conformance.js"));

const CAPS = ["initialize", "authenticate", "session/new", "session/load", "session/prompt",
  "sessions/*", "fork", "load:replay", "set_mode", "set_config", "cancel", "logout",
  "message*", "tool_call*", "usage", "permission", "plan", "slash_cmds",
  "fs/*", "terminal/*", "elicitation", "providers", "nes", "mcp"];

// Reports also carry a positional cells array, but positions shift whenever
// columns are added — rebuild cells from the keyed methods map so reports from
// any probe version align with the current columns.
const CELL_MAP = {
  "initialize": ["initialize"],
  "authenticate": ["authenticate"],
  "session/new": ["session/new"],
  "session/load": ["session/load"],
  "session/prompt": ["session/prompt"],
  "sessions/*": ["session/list", "session/resume", "session/close", "session/delete"],
  "fork": ["session/fork"],
  "load:replay": ["load:replay"],
  "set_mode": ["set_mode"],
  "set_config": ["set_config"],
  "cancel": ["cancel"],
  "logout": ["logout"],
  "message*": ["update:message"],
  "tool_call*": ["update:tool_call"],
  "usage": ["update:usage"],
  "permission": ["request_permission"],
  "plan": ["update:plan"],
  "slash_cmds": ["update:commands"],
  "fs/*": ["fs/read_text_file", "fs/write_text_file"],
  "terminal/*": ["terminal/*"],
  "elicitation": ["elicitation"],
  "providers": ["providers"],
  "nes": ["nes"],
  "mcp": ["mcp"],
};
const RANK = { pass: 3, partial: 2, na: 1, fail: 0 };
function cellsFromMethods(methods) {
  return CAPS.map((col) => {
    let w = null;
    for (const k of CELL_MAP[col] ?? []) {
      const r = methods?.[k];
      if (!r) continue;
      if (w === null || RANK[r.status] < RANK[w.status]) w = r;
    }
    if (!w) return -1;
    return w.status === "pass" ? 1 : w.status === "partial" ? 2 : w.status === "fail" ? 0 : -1;
  });
}

// registry: name → entry. Sources: registry/*.json (hand-written, incl.
// selftest fixtures) and registry/agents/*.json (synced from the official
// ACP registry). selftest entries are probed in CI but never published.
const registry = {};
function loadRegistryDir(dir) {
  if (!existsSync(dir)) return;
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".json") && !f.startsWith("_"))) {
    try {
      const e = JSON.parse(readFileSync(join(dir, f), "utf8"));
      if (e.name) registry[e.name] = e;
    } catch (e) {
      console.warn(`skip ${dir}/${f}: ${e.message}`);
    }
  }
}
loadRegistryDir(registryDir);
loadRegistryDir(join(registryDir, "agents"));

const harnesses = [];
if (existsSync(reportsDir)) {
  for (const f of readdirSync(reportsDir).filter((f) => f.endsWith(".report.json"))) {
    let r;
    try {
      r = JSON.parse(readFileSync(join(reportsDir, f), "utf8"));
    } catch (e) {
      console.warn(`skip ${f}: ${e.message}`);
      continue;
    }
    const reg = registry[r.harness] ?? {};
    if (reg.selftest) {
      console.log(`  (selftest, not published: ${r.harness})`);
      continue;
    }
    harnesses.push({
      n: reg.display ?? reg.name ?? r.harness,
      v: [reg.vendor, r.agentVersion ? `v${r.agentVersion}` : null].filter(Boolean).join(" — "),
      desc: reg.description ?? null,
      icon: reg.icon ?? null,
      url: reg.website ?? (reg.repo ? `https://github.com/${reg.repo}` : null),
      tier: r.tier,
      cells: r.methods ? cellsFromMethods(r.methods) : r.cells,
      notes: r.notes ?? {},
      score: r.score,
      version: r.agentVersion,
      probedAt: r.probedAt,
      run: reg.run ?? null,
      repo: reg.repo ?? null,
      dishonesty: r.dishonesty ?? [],
      violations: r.violations ?? [],
      star: r.tier === "verified" && r.score === 100 ? 1 : 0,
      _file: f,
    });
  }
}

harnesses.sort((a, b) => b.score - a.score);

const payload = {
  generatedAt: new Date().toISOString(),
  caps: CAPS,
  harnesses: harnesses.map(({ _file, ...h }) => h),
};

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// generated by tools/aggregate.mjs — do not edit\n` +
    `window.__ACP_WALL__ = ${JSON.stringify(payload, null, 2)};\n`
);
console.log(`aggregated ${harnesses.length} report(s) → ${out}`);
for (const h of harnesses) console.log(`  ${h.tier.padEnd(8)} ${String(h.score).padStart(3)}  ${h.n}`);
