#!/usr/bin/env node
// Publish current evidence and explicitly identified historical records.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CAPS, wallRow } from './ranking.mjs';
import { COLUMNS, METHODOLOGY_VERSION, cellsFromMethods, summarize, runState, STATUS } from '../probe/src/evidence.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const arg = (flag, fallback) => { const i = process.argv.indexOf(flag); return i >= 0 ? process.argv[i + 1] : fallback; };
const reportsDir = resolve(root, arg('--reports', 'probe/reports'));
const registryDir = resolve(root, arg('--registry', 'registry'));
const out = resolve(root, arg('--out', 'data/conformance.js'));
const previous = resolve(root, arg('--previous', out));
const publicDir = join(dirname(out), 'reports');
const read = p => JSON.parse(readFileSync(p, 'utf8'));
const registry = new Map();
const overrides = new Map();
for (const dir of [registryDir, join(registryDir, 'agents')]) {
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir).filter(f => f.endsWith('.json') && !f.startsWith('_'))) {
    const entry = read(join(dir, f));
    if (entry.name) registry.set(entry.name, entry);
  }
}
const ovDir = join(registryDir, 'overrides');
if (existsSync(ovDir)) for (const f of readdirSync(ovDir).filter(f => f.endsWith('.json'))) overrides.set(f.slice(0, -5), read(join(ovDir, f)));

const rows = new Map();
function historical(row) {
  if (row.reportVersion === 2 && row.methodologyVersion === METHODOLOGY_VERSION) return row;
  return { ...row, state: 'legacy', reportVersion: row.reportVersion ?? 1,
    methodologyVersion: row.methodologyVersion ?? '1 (historical)',
    historicalNotes: row.historicalNotes ?? row.notes ?? {}, summary: null };
}

if (existsSync(previous)) {
  const src = readFileSync(previous, 'utf8');
  const data = JSON.parse(src.slice(src.indexOf('=') + 1).trim().replace(/;$/, ''));
  for (const row of data.harnesses ?? []) {
    const id = row.id ?? [...registry].find(([, e]) => (e.display ?? e.name) === row.n)?.[0];
    if (id && registry.has(id) && !registry.get(id).selftest) rows.set(id, historical({ ...row, id }));
  }
}
mkdirSync(publicDir, { recursive: true });
if (existsSync(reportsDir)) for (const file of readdirSync(reportsDir).filter(f => f.endsWith('.report.json'))) {
  const r = read(join(reportsDir, file));
  const reg = registry.get(r.harness);
  if (!reg || reg.selftest) continue;
  if (!/^[a-zA-Z0-9._-]+$/.test(r.harness)) throw new Error(`Invalid report id in ${file}`);
  const prior = rows.get(r.harness);
  if (prior?.probedAt && Date.parse(prior.probedAt) > Date.parse(r.probedAt)) continue;
  const base = {
    id: r.harness, n: reg.display ?? reg.name, v: reg.vendor, desc: reg.description,
    icon: reg.icon, url: reg.website ?? (reg.repo ? `https://github.com/${reg.repo}` : null), repo: reg.repo,
    version: r.agentVersion, probedAt: r.probedAt,
    lody: r.lody, ext: r.ext, lodyAdapter: overrides.get(r.harness)?.lodyAdapter ?? reg.lodyAdapter ?? null,
  };
  if (r.reportVersion !== 2 || r.methodologyVersion !== METHODOLOGY_VERSION) {
    rows.set(r.harness, historical({ ...base, notes: r.notes, cells: r.cells, score: r.score, tier: r.tier, methods: r.methods })); continue;
  }
  for (const [key, result] of Object.entries(r.methods ?? {})) if (!STATUS[result.status]) throw new Error(`Unknown evidence status: ${file}:${key}`);
  const summary = summarize(r.methods);
  const state = runState(summary, r.setup, r.violations, r.methods);
  const { transcript, ...publicReport } = r;
  // Full wire transcripts remain in the CI artifact. The public report carries
  // method outcomes, timestamped attempts, schema diagnostics and provenance.
  writeFileSync(join(publicDir, `${r.harness}.json`), JSON.stringify(publicReport, null, 2) + '\n');
  rows.set(r.harness, {
    ...base, reportVersion: 2, methodologyVersion: r.methodologyVersion, schemaSha256: r.schemaSha256,
    state, summary, cells: cellsFromMethods(r.methods), methods: r.methods,
    setup: r.setup, environment: r.environment, transport: r.transport, advertised: r.advertised,
    violations: r.violations ?? [], claimMismatches: r.claimMismatches ?? [],
    scenarios: r.scenarios ?? [], uncertaintyReasons: r.uncertaintyReasons ?? {}, attempts: r.attempts ?? [],
    reportUrl: `data/reports/${r.harness}.json`,
  });
}
const payload = {
  formatVersion: 2, methodologyVersion: METHODOLOGY_VERSION, generatedAt: new Date().toISOString(),
  caps: CAPS, harnesses: [...rows.values()].map(row => wallRow(row, registry.get(row.id))).sort((a, b) => b.score - a.score || a.n.localeCompare(b.n)),
};
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// Generated by tools/aggregate.mjs. See docs/measurement.md.\nwindow.__ACP_WALL__ = ${JSON.stringify(payload, null, 2)};\n`);
console.log(`Published ${rows.size} records (${[...rows.values()].filter(r => r.state === 'legacy').length} need re-probing) → ${out}`);
